Friendship v2
Flakster/ror-social-scaffold pull request #12
Opened 2020-06-02 16:48 UTC by Flakster

# This PR includes:

- Improvement of the performance of queries by Implementing friendship with 2 rows for mutual friendship.

Closes #3

2020-06-02 21:38 UTC, nikasulo requested changes
# Great work @Flakster and @AlfredoElizarraras!
Please consider my comments below towards aligning your project with the requirements for this task. A few of these below have been implemented in your own way and I commend your efforts, however, there are more optimal ways to do a few things, hence the comments below:

#### Friends and own posts 
Please consider the following method to curate the posts for the user feed.
![screenshot](https://images2.imgbox.com/6e/f1/HYImiKNd_o.png)

#### Inverted friendships and friend requests
Please consider the following way to define friend requests
![screenshot](https://images2.imgbox.com/f2/02/nGLZztjD_o.png)

#### Pending friendships and pending friends
![screenshot](https://images2.imgbox.com/39/da/Oqpm06u7_o.png)

#### Confirmed friendships and friends
![screenshot](https://images2.imgbox.com/f1/f0/lyO2e3LM_o.png)

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-06-03 20:50 UTC, AlfredoElizarraras commented
Hello @Oluwadamilareolusakin :wave: 
Thanks for all your feedback :pray: it was really interesting finding another way to implement those associations. :eyes: 
The only funny thing is we end up with the same associations we have once asked to change but with scope inside the association that we didn't know it can be there. :dango: :raised_hands:

2020-06-04 07:20 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-06-04 15:21 UTC, Flakster commented
Thanks for your review @suretrust :+1:

2020-06-04 15:21 UTC, merged